version: "2.3"


services:
  arduino:
    build: .
    environment:
      - ARDUINO_BOARD
      - ARDUINO_PORT
    volumes:
      - ./:/mnt/cabot-handle
      - /dev:/dev
      - /sys/devices:/sys/devices
# required for display or device
    privileged: true
# device, bluetooth
    devices:
      - /dev/dri
# device, bluetooth
    network_mode: host
    working_dir: /mnt/cabot-handle
    command:
      - "bash"
